### ISSUE TITLE
[Crash] Negative array crash

### ISSUE THREAD

**Issue by DWX12** [OreCruncher/OreLib#2]
Got this crash, not sure what the cause of it is:

https://paste.dimdev.org/pipomogopu.mccrash

**Comment by OreCruncher** [comment]
Does this always happen, or just sporadically?

EDIT:  Just noticed this in the log:
```
All players: 1 total; [GCEntityClientPlayerMP['DWX'/2114, l='MpServer', x=168324348864245050000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.00, y=3292682824625585000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.00, z=1147787978463155600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.00]]
 ```
I would say the player coordinates are all screwed up.  This is what is causing the math to go wrong when calculating the chunk.  So the question is what is screwing up the coords?

EDIT2:  Also post your dsurround.cfg.  There are some parameters in there which could influence caching behavior.  They do not have anything to do with the player coords - DS does nothing with them except read.

**Comment by DWX12** [comment]
Believe I sorted it out. It ended up being a weird combo of a few different issues (or atleast getting feedback saying it's mod X that's causing the problem). One thing, I had in a mod that wasn't in the server and the client would just hang at the lovely dirt screen. Before that, it was throwing the Journey Map error that has a mod devoted to fixing an issue with it.

I'm still updating and trying to resolve other issues, all the fun stuff that comes with building and trying to get a server to run properly.

Thanks for all your help OC.

**Comment by OreCruncher** [comment]
Glad you figured it out.  Let me know how things turn out.

**Comment by DWX12** [comment]
Apparently it was different issues and still didn't figure out the exact cause. I went through removing and readding mods and then the problem went away. So I really have no clue as to what the real issue is. If it comes along again, I'll let you know.

**Comment by OreCruncher** [comment]
Thanks!
