### ISSUE TITLE
Crash when opening chests on a AdvancedRocketry rocket

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [OreCruncher/OreLib#5]
*Mod Version: 3.5.4.3*

*Forge Version: 14.23.5.2816*

*Link to crash log (if applicable): https://paste.dimdev.org/vazunirako.mccrash*

*Description:*
The game crashes when trying to open an chest on assembled advanced rocketry rockets.
**Edit:** can also happen when opening guidiance computer or other things

**Comment by OreCruncher** [comment]
Pushed OreLib-1.12.2-3.5.2.3 to CurseForge.
