### ISSUE TITLE
[OreLib 1.12.2-3.6.0.0] Server crash on Login / Update Check. 

### ISSUE THREAD

**Issue by JoelZBub** [OreCruncher/OreLib#6]
Forge 1.12.2-14.23.5.2838
Dynamic Surroundings 1.12.2-3.6.0.0
OreLib 1.12.2-3.6.0.0

Player logging in to dedicated server with the above mods crashes the server.

Server Crash Report : https://hatebin.com/joviyyfrvr

**Comment by OreCruncher** [comment]
Uh, this is weird.  This a pack you put together yourself?

EDIT:  Also, can you post your client log?  Sometimes it is a different error than what is in crash dump.

**Comment by OreCruncher** [comment]
Try this one: https://github.com/OreCruncher/OreLib/releases/tag/1.12.2-3.6.0.1

**Comment by cashnub** [comment]
https://pastebin.com/raw/1nxYYvnM

Got what looks like the same issue
Running 3.6.0.1
Dropping crash report to hopefully make things easier for you

Crash occurs on hitting play on the launcher, actual Minecraft window never opens

**Comment by nephatrine** [comment]
Was getting this issue (same as JoelZBub) on 3.6.0.0, but updating to 3.6.0.1 resolved it for me. The error cashnub is getting looks like a different issue entirely and doesn't match the other crash report or issue description.

**Comment by cashnub** [comment]
Just Tried running MC with all mods removed from the appdata folder including optifine, leaving only orelib and dynamic surroundings. Same issue occured, Minecraft will not open since updating both of those mods.

**Comment by JoelZBub** [comment]
This is an assortment of mods that I was using to test a completely different issue. I did not test with *only* orelib and dsurround. 

Using 3.6.0.1, I am able to connect to my test server with no crash.

 Thanks!

**Comment by OreCruncher** [comment]
@cashnub its an entirely different issue.  Update to at least Forge 2779.  You are apparently running Forge 2768.

**Comment by cashnub** [comment]
I'm a dumb :/

**Comment by OreCruncher** [comment]
No worries.  I don't think you would have gotten to the display where Forge informs you of the dependency.  This particular piece of code executes before that.
